const $=id=>document.getElementById(id);
const video=$('video'), canvas=$('overlay'), ctx=canvas.getContext('2d');
const startBtn=$('startBtn'), stopBtn=$('stopBtn'), controlBtn=$('controlBtn');
const cursor=$('virtualCursor'), mascot=$('mascot'), speech=$('speech');
const playground=$('playground'), zoomTarget=$('zoomTarget'), zoomValue=$('zoomValue'), toast=$('actionToast'), labStatus=$('labStatus'), labPointer=$('labPointer');
let camera=null,running=false,control=false,demo=false,lastT=performance.now(),fpsSmooth=0;
let xp=0,level=1,combo=0,lastGesture='',gestureSince=0,mission=0,missionProgress=0,soundOn=true;
let smoothLab={x:.5,y:.5},grabbed=null,grabOffset={x:0,y:0},pinchPrev=false;
let motionHistory=[],lastSwipe=0,lastFist=0,zoomBase=null,zoomScale=1,lastInteraction=0;
const missions=[
  {key:'camera',title:'Activa la cámara',desc:'Comienza el entrenamiento mostrando tu mano.'},
  {key:'open',title:'Haz una mano abierta',desc:'Mantén la mano abierta durante unos segundos.'},
  {key:'pinch',title:'Haz una pinza',desc:'Une pulgar e índice para seleccionar.'},
  {key:'victory',title:'Cierra con victoria',desc:'Haz el gesto de victoria para completar el entrenamiento.'}
];
const gestureInfo={none:{emoji:'🖐️',name:'ESPERANDO',desc:'Muestra una mano',action:'Esperando gesto'},hand:{emoji:'🖐️',name:'MANO',desc:'Seguimiento activo',action:'Mover'},point:{emoji:'☝️',name:'SEÑALAR',desc:'Mueve el puntero',action:'Cursor'},pinch:{emoji:'🤏',name:'PINZA',desc:'Agarrar / arrastrar',action:'Agarrar'},open:{emoji:'✋',name:'MANO ABIERTA',desc:'Swipe lateral',action:'Mover'},fist:{emoji:'✊',name:'PUÑO',desc:'Cerrar selección',action:'Cerrar'},victory:{emoji:'✌️',name:'VICTORIA',desc:'Cambiar modo',action:'Cambiar modo'}};
function log(msg,type=''){const d=document.createElement('div');d.textContent=`[${new Date().toLocaleTimeString()}] ${msg}`;if(type)d.className=type;$('log').prepend(d)}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1100)}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function fingerUp(lm,tip,pip){return lm[tip].y<lm[pip].y}
function classify(lm){const scale=Math.max(dist(lm[0],lm[9]),.001);if(dist(lm[4],lm[8])/scale<.38)return'pinch';const up=[fingerUp(lm,8,6),fingerUp(lm,12,10),fingerUp(lm,16,14),fingerUp(lm,20,18)],n=up.filter(Boolean).length;if(n>=3)return'open';if(n===0)return'fist';if(up[0]&&up[1]&&!up[2]&&!up[3])return'victory';if(up[0]&&!up[1]&&!up[2]&&!up[3])return'point';return'hand'}
function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);
function addXP(n){xp+=n;if(xp>=100){xp-=100;level++;log(`Subiste al nivel ${level}`,'ok');speech.innerHTML=`⚡ ¡Nivel ${level}! Cada vez controlas mejor tus gestos.`}updateXP()}
function updateXP(){$('level').textContent=level;$('xpText').textContent=`${xp} / 100 XP`;$('xpBar').style.width=xp+'%';$('energyBar').style.width=Math.min(100,xp+20)+'%';$('energyText').textContent=Math.min(100,xp+20)+'%'}
function updateMission(){const m=missions[mission];$('missionIndex').textContent=`${mission+1}/${missions.length}`;$('missionTitle').textContent=m.title;$('missionDesc').textContent=m.desc;$('missionBar').style.width=missionProgress+'%'}
function completeMission(){if(mission>=missions.length)return;missionProgress=100;updateMission();addXP(20);log(`Misión completada: ${missions[mission].title}`,'ok');mascot.classList.add('happy');setTimeout(()=>mascot.classList.remove('happy'),900);if(mission<missions.length-1){mission++;missionProgress=0;setTimeout(updateMission,400)}else speech.innerHTML='🏆 ¡Entrenamiento completado! Prueba ahora el modo demo.'}
function setGesture(key){const g=gestureInfo[key]||gestureInfo.hand;$('gestureLabel').textContent=`${g.emoji} ${g.name}`;$('gestureAction').textContent=g.action;$('gestureEmoji').textContent=g.emoji;$('gestureName').textContent=g.name;$('gestureDesc').textContent=g.desc;document.querySelectorAll('.gesture-cards button').forEach(b=>b.classList.toggle('active',b.dataset.gesture===key));if(key!==lastGesture){lastGesture=key;gestureSince=Date.now();if(!['hand','none'].includes(key)){combo++;$('comboMetric').textContent='x'+combo;log(`Gesto: ${g.name}`,'ok')}speech.innerHTML=key==='pinch'?'🤏 Pinza detectada: si estás cerca de una tarjeta, la agarro.':key==='open'?'👋 Mano abierta: muévela rápido a un lado para hacer swipe.':key==='fist'?'✊ Puño detectado: cierro la tarjeta seleccionada.':key==='point'?'☝️ Estoy siguiendo tu mano.':'Te estoy viendo 👀'}if(missions[mission]?.key===key){missionProgress=Math.min(100,((Date.now()-gestureSince)/1200)*100);updateMission();if(missionProgress>=100)completeMission()}}
function handToLab(lm){const p=lm[8];const tx=Math.max(.03,Math.min(.97,1-p.x));const ty=Math.max(.05,Math.min(.95,p.y));smoothLab.x=smoothLab.x*.68+tx*.32;smoothLab.y=smoothLab.y*.68+ty*.32;const r=playground.getBoundingClientRect();return{x:smoothLab.x*r.width,y:smoothLab.y*r.height,nx:smoothLab.x,ny:smoothLab.y}}
function updatePointers(pos,key){if(!demo){labPointer.style.opacity='0';cursor.style.display='none';return}const pr=playground.getBoundingClientRect();labPointer.style.opacity='1';labPointer.style.left=pos.x+'px';labPointer.style.top=pos.y+'px';labPointer.classList.toggle('pinching',key==='pinch');cursor.style.display='block';cursor.style.left=(pr.left+pos.x)+'px';cursor.style.top=(pr.top+pos.y)+'px';cursor.classList.toggle('pinching',key==='pinch')}
function cardCenter(card){return{x:card.offsetLeft+card.offsetWidth/2,y:card.offsetTop+card.offsetHeight/2}}
function nearestCard(x,y,max=180){let best=null,bestD=Infinity;document.querySelectorAll('.float-card:not(.closed)').forEach(c=>{const p=cardCenter(c),d=Math.hypot(x-p.x,y-p.y);if(d<bestD){best=c;bestD=d}});return bestD<=max?best:null}
function startGrab(card,x,y){grabbed=card;grabbed.classList.add('grabbed');grabOffset.x=x-card.offsetLeft;grabOffset.y=y-card.offsetTop;showToast(`🤏 ${card.dataset.card} capturado`);speech.innerHTML=`⚡ ¡${card.dataset.card} capturado! Mueve tu mano sin soltar la pinza.`;log(`Objeto agarrado: ${card.dataset.card}`,'ok');lastInteraction=Date.now()}
function dragCard(x,y){if(!grabbed)return;const w=grabbed.offsetWidth,h=grabbed.offsetHeight;let left=x-grabOffset.x,top=y-grabOffset.y;left=Math.max(0,Math.min(playground.clientWidth-w,left));top=Math.max(0,Math.min(playground.clientHeight-h,top));grabbed.style.left=left+'px';grabbed.style.top=top+'px';grabbed.style.right='auto';grabbed.style.bottom='auto'}
function releaseGrab(){if(!grabbed)return;grabbed.classList.remove('grabbed');showToast('✨ Objeto soltado');log(`Objeto soltado: ${grabbed.dataset.card}`,'ok');grabbed=null}
function detectSwipe(lm,key){if(!demo||key!=='open')return;const now=Date.now(),x=1-lm[9].x;motionHistory.push({x,t:now});motionHistory=motionHistory.filter(v=>now-v.t<420);if(motionHistory.length<5||now-lastSwipe<1000)return;const dx=x-motionHistory[0].x;if(Math.abs(dx)>.14){lastSwipe=now;const dir=dx>0?'derecha':'izquierda';showToast(`👋 Swipe ${dir}`);speech.innerHTML=`👋 ¡Swipe a la ${dir}!`;log(`Swipe ${dir}`,'ok');const cards=[...document.querySelectorAll('.float-card:not(.closed)')];cards.forEach((c,i)=>{const shift=dx>0?70:-70;c.animate([{transform:'translateX(0)'},{transform:`translateX(${shift}px)`},{transform:'translateX(0)'}],{duration:320,easing:'ease-out'});});motionHistory=[]}}
function handleFist(pos){if(!demo||Date.now()-lastFist<1100)return;lastFist=Date.now();const active=grabbed||nearestCard(pos.x,pos.y,220);if(active){active.classList.add('closed');releaseGrab();showToast(`✊ ${active.dataset.card} cerrado`);speech.innerHTML=`✊ Cerré ${active.dataset.card}.`;log(`Panel cerrado: ${active.dataset.card}`,'ok')}}
function handleZoom(list){if(!demo||list.length<2){zoomBase=null;return}const a=list[0][9],b=list[1][9],d=dist(a,b);if(!zoomBase){zoomBase=d;return}const delta=(d-zoomBase)*2.1;zoomScale=Math.max(.6,Math.min(2,zoomScale+delta));zoomBase=d;zoomTarget.style.transform=`translate(-50%,-50%) scale(${zoomScale})`;zoomValue.textContent=Math.round(zoomScale*100)+'%';if(Math.abs(delta)>.012)showToast(`👐 Zoom ${Math.round(zoomScale*100)}%`)}
function interact(lm,key){const pos=handToLab(lm);updatePointers(pos,key);if(!demo)return;const pinching=key==='pinch';if(pinching&&!pinchPrev&&!grabbed){const c=nearestCard(pos.x,pos.y,190);if(c)startGrab(c,pos.x,pos.y);else{showToast('🤏 Acerca la mano a una tarjeta');speech.innerHTML='🤏 Pinza detectada. Acerca el puntero a una tarjeta.'}}if(pinching&&grabbed)dragCard(pos.x,pos.y);if(!pinching&&pinchPrev)releaseGrab();pinchPrev=pinching;if(key==='open')detectSwipe(lm,key);else motionHistory=[];if(key==='fist')handleFist(pos)}
function resetLab(){document.querySelectorAll('.float-card').forEach(c=>{c.classList.remove('closed','grabbed');c.style.left='';c.style.top='';c.style.right='';c.style.bottom=''});grabbed=null;pinchPrev=false;zoomBase=null;zoomScale=1;zoomTarget.style.transform='translate(-50%,-50%) scale(1)';zoomValue.textContent='100%';showToast('↻ Laboratorio reiniciado');log('Laboratorio reiniciado')}
const hands=new Hands({locateFile:file=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`});
hands.setOptions({maxNumHands:2,modelComplexity:1,minDetectionConfidence:.65,minTrackingConfidence:.6});
hands.onResults(results=>{const now=performance.now(),dt=now-lastT;lastT=now;const fps=dt>0?1000/dt:0;fpsSmooth=fpsSmooth*.85+fps*.15;const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);const list=results.multiHandLandmarks||[],handed=results.multiHandedness||[];let conf=0,key='none';list.forEach((lm,i)=>{drawConnectors(ctx,lm,HAND_CONNECTIONS,{color:'#42ddff',lineWidth:2});drawLandmarks(ctx,lm,{color:'#f7fbff',fillColor:'#1677ff',lineWidth:1,radius:3});const g=classify(lm);if(i===0){key=g;interact(lm,g)}conf=Math.max(conf,(handed[i]?.score||0)*100)});handleZoom(list);if(!list.length){cursor.style.display='none';labPointer.style.opacity='0';releaseGrab();pinchPrev=false;combo=0;$('comboMetric').textContent='x0'}setGesture(list.length?key:'none');$('handsPill').textContent=`MANOS: ${list.length}`;$('handsMetric').textContent=list.length;$('confidenceMetric').textContent=`${Math.round(conf)}%`;$('confidencePill').textContent=`CONFIANZA: ${Math.round(conf)}%`;$('fpsMetric').textContent=Math.round(fpsSmooth);$('fpsPill').textContent=`FPS: ${Math.round(fpsSmooth)}`;$('trackingState').textContent=list.length?'TRACKING LOCKED':'BUSCANDO';if(missions[mission]?.key==='camera'&&running)completeMission()});
async function start(){if(running)return;try{resize();camera=new Camera(video,{onFrame:async()=>{await hands.send({image:video})},width:1280,height:720});await camera.start();running=true;$('emptyState').classList.add('hidden');$('statusDot').classList.add('on');$('statusText').textContent='Cámara activa';startBtn.disabled=true;stopBtn.disabled=false;controlBtn.disabled=false;log('Cámara iniciada correctamente','ok');speech.innerHTML='👀 ¡Ya te veo! Ahora activa Modo demo para interactuar.';if(missions[mission]?.key==='camera')completeMission()}catch(e){log('No se pudo iniciar la cámara','warn');speech.innerHTML='⚠️ Necesito permiso de cámara para entrenar.';console.error(e)}}
function stop(){if(camera)camera.stop();running=false;control=false;demo=false;cursor.style.display='none';labPointer.style.opacity='0';releaseGrab();playground.classList.remove('demo-on');labStatus.textContent='Activa Modo demo';$('emptyState').classList.remove('hidden');$('statusDot').classList.remove('on');$('statusText').textContent='Cámara detenida';startBtn.disabled=false;stopBtn.disabled=true;controlBtn.disabled=true;controlBtn.textContent='◎ Activar control';$('demoBtn').textContent='✨ Modo demo';log('Cámara detenida');speech.innerHTML='😴 Cámara apagada. Avísame cuando quieras seguir.'}
startBtn.onclick=start;stopBtn.onclick=stop;controlBtn.onclick=()=>{control=!control;controlBtn.textContent=control?'◎ Desactivar control':'◎ Activar control';log(`Control virtual ${control?'activado':'desactivado'}`,'ok')};
$('trainingBtn').onclick=()=>{mission=0;missionProgress=0;updateMission();speech.innerHTML='🎮 Modo entrenamiento listo. Completa las 4 misiones.';log('Modo entrenamiento reiniciado')};
$('demoBtn').onclick=()=>{if(!running){speech.innerHTML='📷 Primero inicia la cámara.';showToast('Primero inicia la cámara');return}demo=!demo;control=demo;playground.classList.toggle('demo-on',demo);$('demoBtn').textContent=demo?'✨ Salir modo demo':'✨ Modo demo';labStatus.textContent=demo?'INTERACCIÓN ACTIVA':'Activa Modo demo';controlBtn.textContent=control?'◎ Desactivar control':'◎ Activar control';speech.innerHTML=demo?'✨ ¡Listo! Mira el puntero dentro del laboratorio y mueve tu mano.':'Modo demo desactivado.';showToast(demo?'✨ Mueve tu mano dentro del laboratorio':'Modo demo apagado');log(`Modo demo ${demo?'activado':'desactivado'}`,'ok');if(demo)setTimeout(()=>$('interactionLab').scrollIntoView({behavior:'smooth',block:'center'}),100)};
$('resetLabBtn').onclick=resetLab;$('clearLog').onclick=()=>{$('log').innerHTML='<div>Registro limpiado.</div>'};$('soundBtn').onclick=()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'🔊':'🔇'};$('fullscreenBtn').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()};
updateXP();updateMission();