const $=id=>document.getElementById(id);
const video=$('video'), canvas=$('overlay'), ctx=canvas.getContext('2d');
const startBtn=$('startBtn'), stopBtn=$('stopBtn'), controlBtn=$('controlBtn');
const cursor=$('virtualCursor'), mascot=$('mascot'), speech=$('speech');
const playground=$('playground'), zoomTarget=$('zoomTarget'), zoomValue=$('zoomValue'), toast=$('actionToast'), labStatus=$('labStatus');
let camera=null,running=false,control=false,demo=false,lastClick=0,lastT=performance.now(),fpsSmooth=0;
let xp=0,level=1,combo=0,lastGesture='',gestureSince=0,mission=0,missionProgress=0,soundOn=true;
let smoothX=innerWidth/2,smoothY=innerHeight/2,grabbed=null,grabOffset={x:0,y:0};
let motionHistory=[],lastSwipe=0,lastFist=0,zoomBase=null,zoomScale=1;
const missions=[
  {key:'camera',title:'Activa la cámara',desc:'Comienza el entrenamiento mostrando tu mano.'},
  {key:'open',title:'Haz una mano abierta',desc:'Mantén la mano abierta durante unos segundos.'},
  {key:'pinch',title:'Haz una pinza',desc:'Une pulgar e índice para seleccionar.'},
  {key:'victory',title:'Cierra con victoria',desc:'Haz el gesto de victoria para completar el entrenamiento.'}
];
const gestureInfo={none:{emoji:'🖐️',name:'ESPERANDO',desc:'Muestra una mano',action:'Esperando gesto'},hand:{emoji:'🖐️',name:'MANO',desc:'Seguimiento activo',action:'Mano detectada'},point:{emoji:'☝️',name:'SEÑALAR',desc:'Mueve el cursor virtual',action:'Cursor'},pinch:{emoji:'🤏',name:'PINZA',desc:'Clic / Arrastrar',action:'Agarrar'},open:{emoji:'✋',name:'MANO ABIERTA',desc:'Confirmar / Swipe',action:'Mover'},fist:{emoji:'✊',name:'PUÑO',desc:'Cerrar selección',action:'Cerrar'},victory:{emoji:'✌️',name:'VICTORIA',desc:'Cambiar modo',action:'Cambiar modo'}};
function log(msg,type=''){const d=document.createElement('div');d.textContent=`[${new Date().toLocaleTimeString()}] ${msg}`;if(type)d.className=type;$('log').prepend(d)}
function showToast(msg){toast.textContent=msg;toast.style.opacity='1';clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.style.opacity='.85',900)}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function fingerUp(lm,tip,pip){return lm[tip].y<lm[pip].y}
function classify(lm){const scale=Math.max(dist(lm[0],lm[9]),.001);if(dist(lm[4],lm[8])/scale<.32)return'pinch';const up=[fingerUp(lm,8,6),fingerUp(lm,12,10),fingerUp(lm,16,14),fingerUp(lm,20,18)],n=up.filter(Boolean).length;if(n===4)return'open';if(n===0)return'fist';if(up[0]&&up[1]&&!up[2]&&!up[3])return'victory';if(up[0]&&!up[1]&&!up[2]&&!up[3])return'point';return'hand'}
function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);
function addXP(n){xp+=n;if(xp>=100){xp-=100;level++;log(`Subiste al nivel ${level}`,'ok');speech.innerHTML=`⚡ ¡Nivel ${level}! Cada vez controlas mejor tus gestos.`}updateXP()}
function updateXP(){$('level').textContent=level;$('xpText').textContent=`${xp} / 100 XP`;$('xpBar').style.width=xp+'%';$('energyBar').style.width=Math.min(100,xp+20)+'%';$('energyText').textContent=Math.min(100,xp+20)+'%'}
function updateMission(){const m=missions[mission];$('missionIndex').textContent=`${mission+1}/${missions.length}`;$('missionTitle').textContent=m.title;$('missionDesc').textContent=m.desc;$('missionBar').style.width=missionProgress+'%'}
function completeMission(){if(mission>=missions.length)return;missionProgress=100;updateMission();addXP(20);log(`Misión completada: ${missions[mission].title}`,'ok');mascot.classList.add('happy');setTimeout(()=>mascot.classList.remove('happy'),900);if(mission<missions.length-1){mission++;missionProgress=0;setTimeout(updateMission,500)}else speech.innerHTML='🏆 ¡Entrenamiento completado! Prueba ahora el modo demo.'}
function setGesture(key){const g=gestureInfo[key]||gestureInfo.hand;$('gestureLabel').textContent=`${g.emoji} ${g.name}`;$('gestureAction').textContent=g.action;$('gestureEmoji').textContent=g.emoji;$('gestureName').textContent=g.name;$('gestureDesc').textContent=g.desc;document.querySelectorAll('.gesture-cards button').forEach(b=>b.classList.toggle('active',b.dataset.gesture===key));if(key!==lastGesture){lastGesture=key;gestureSince=Date.now();if(key!=='hand'&&key!=='none'){combo++;$('comboMetric').textContent='x'+combo;log(`Gesto: ${g.name}`,'ok')}mascot.className='mascot power';speech.innerHTML=key==='pinch'?'🤏 ¡Pinza! Puedes agarrar una tarjeta.':key==='open'?'👋 Mano abierta: mueve rápido para hacer swipe.':key==='victory'?'✌️ ¡Victoria!':key==='fist'?'✊ Puño: cerraré la selección.':key==='point'?'☝️ Señala y mueve el cursor.':'Te estoy viendo 👀';setTimeout(()=>mascot.className='mascot idle',350)}if(missions[mission]?.key===key){missionProgress=Math.min(100,((Date.now()-gestureSince)/1200)*100);updateMission();if(missionProgress>=100)completeMission()}}
function getPointer(lm){const p=lm[8],tx=(1-p.x)*innerWidth,ty=p.y*innerHeight;smoothX=smoothX*.72+tx*.28;smoothY=smoothY*.72+ty*.28;return{x:smoothX,y:smoothY}}
function updateCursor(lm,key){if(!control){cursor.style.display='none';return null}const pos=getPointer(lm);cursor.style.display='block';cursor.style.left=pos.x+'px';cursor.style.top=pos.y+'px';cursor.classList.toggle('pinching',key==='pinch');return pos}
function pickCard(x,y){const el=document.elementFromPoint(x,y);return el?.closest?.('.float-card')||null}
function startGrab(card,x,y){grabbed=card;grabbed.classList.add('grabbed');const r=grabbed.getBoundingClientRect();grabOffset.x=x-r.left;grabOffset.y=y-r.top;showToast(`🤏 ${grabbed.dataset.card} capturado`);speech.innerHTML='⚡ ¡Objeto capturado! Muévelo con tu mano.';log(`Objeto agarrado: ${grabbed.dataset.card}`,'ok')}
function dragCard(x,y){if(!grabbed)return;const pr=playground.getBoundingClientRect();const w=grabbed.offsetWidth,h=grabbed.offsetHeight;let left=x-pr.left-grabOffset.x,top=y-pr.top-grabOffset.y;left=Math.max(0,Math.min(pr.width-w,left));top=Math.max(0,Math.min(pr.height-h,top));grabbed.style.left=left+'px';grabbed.style.top=top+'px';grabbed.style.right='auto';grabbed.style.bottom='auto'}
function releaseGrab(){if(!grabbed)return;grabbed.classList.remove('grabbed');showToast('✨ Objeto soltado');grabbed=null}
function detectSwipe(lm,key){if(!demo||key!=='open')return;const p=lm[9],x=1-p.x,now=Date.now();motionHistory.push({x,t:now});motionHistory=motionHistory.filter(v=>now-v.t<350);if(motionHistory.length<4||now-lastSwipe<900)return;const dx=x-motionHistory[0].x;if(Math.abs(dx)>.18){lastSwipe=now;const dir=dx>0?'derecha':'izquierda';showToast(`👋 Swipe ${dir}`);speech.innerHTML=`👋 ¡Swipe a la ${dir}!`;log(`Swipe ${dir}`,'ok');const dots=[...document.querySelectorAll('.scene-dots i')],idx=dots.findIndex(d=>d.classList.contains('active'));dots.forEach(d=>d.classList.remove('active'));dots[(idx+(dx>0?1:-1)+dots.length)%dots.length].classList.add('active');playground.animate([{transform:'translateX(0)'},{transform:`translateX(${dx>0?18:-18}px)`},{transform:'translateX(0)'}],{duration:350,easing:'ease-out'})}}
function handleFist(){if(!demo||Date.now()-lastFist<900)return;lastFist=Date.now();const active=grabbed||document.querySelector('.float-card:not(.closed)');if(active){active.classList.add('closed');releaseGrab();showToast('✊ Panel cerrado');speech.innerHTML='✊ Panel cerrado.';log('Panel cerrado con puño','ok')}}
function handleZoom(list){if(!demo||list.length<2){zoomBase=null;return}const a=list[0][9],b=list[1][9],d=dist(a,b);if(!zoomBase){zoomBase=d;return}zoomScale=Math.max(.65,Math.min(1.8,zoomScale+(d-zoomBase)*1.6));zoomBase=d;zoomTarget.style.transform=`translate(-50%,-50%) scale(${zoomScale})`;zoomValue.textContent=Math.round(zoomScale*100)+'%';showToast(`👐 Zoom ${Math.round(zoomScale*100)}%`)}
function interact(lm,key){const pos=updateCursor(lm,key);if(!demo||!pos)return;if(key==='pinch'){if(!grabbed){const c=pickCard(pos.x,pos.y);if(c&&!c.classList.contains('closed'))startGrab(c,pos.x,pos.y)}else dragCard(pos.x,pos.y)}else releaseGrab();if(key==='open')detectSwipe(lm,key);else motionHistory=[];if(key==='fist')handleFist();if(key==='pinch'&&!grabbed&&Date.now()-lastClick>700){lastClick=Date.now();const el=document.elementFromPoint(pos.x,pos.y);if(el&&['BUTTON','A'].includes(el.tagName)){el.click();log('Clic virtual ejecutado','ok')}}}
const hands=new Hands({locateFile:file=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`});
hands.setOptions({maxNumHands:2,modelComplexity:1,minDetectionConfidence:.65,minTrackingConfidence:.6});
hands.onResults(results=>{const now=performance.now(),dt=now-lastT;lastT=now;const fps=dt>0?1000/dt:0;fpsSmooth=fpsSmooth*.85+fps*.15;const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);const list=results.multiHandLandmarks||[],handed=results.multiHandedness||[];let conf=0,key='none';list.forEach((lm,i)=>{drawConnectors(ctx,lm,HAND_CONNECTIONS,{color:'#42ddff',lineWidth:2});drawLandmarks(ctx,lm,{color:'#f7fbff',fillColor:'#1677ff',lineWidth:1,radius:3});const g=classify(lm);if(i===0){key=g;interact(lm,g)}conf=Math.max(conf,(handed[i]?.score||0)*100)});handleZoom(list);if(!list.length){cursor.style.display='none';releaseGrab();combo=0;$('comboMetric').textContent='x0'}setGesture(list.length?key:'none');$('handsPill').textContent=`MANOS: ${list.length}`;$('handsMetric').textContent=list.length;$('confidenceMetric').textContent=`${Math.round(conf)}%`;$('confidencePill').textContent=`CONFIANZA: ${Math.round(conf)}%`;$('fpsMetric').textContent=Math.round(fpsSmooth);$('fpsPill').textContent=`FPS: ${Math.round(fpsSmooth)}`;$('trackingState').textContent=list.length?'TRACKING LOCKED':'BUSCANDO';if(missions[mission]?.key==='camera'&&running)completeMission()});
async function start(){if(running)return;try{resize();camera=new Camera(video,{onFrame:async()=>{await hands.send({image:video})},width:1280,height:720});await camera.start();running=true;$('emptyState').classList.add('hidden');$('statusDot').classList.add('on');$('statusText').textContent='Cámara activa';startBtn.disabled=true;stopBtn.disabled=false;controlBtn.disabled=false;log('Cámara iniciada correctamente','ok');speech.innerHTML='👀 ¡Ya te veo! Muestra tu mano para empezar.';if(missions[mission]?.key==='camera')completeMission()}catch(e){log('No se pudo iniciar la cámara','warn');speech.innerHTML='⚠️ Necesito permiso de cámara para entrenar.';console.error(e)}}
function stop(){if(camera)camera.stop();running=false;control=false;demo=false;cursor.style.display='none';releaseGrab();playground.classList.remove('demo-on');labStatus.textContent='Activa Modo demo';$('emptyState').classList.remove('hidden');$('statusDot').classList.remove('on');$('statusText').textContent='Cámara detenida';startBtn.disabled=false;stopBtn.disabled=true;controlBtn.disabled=true;controlBtn.textContent='◎ Activar control';log('Cámara detenida');speech.innerHTML='😴 Cámara apagada. Avísame cuando quieras seguir.'}
startBtn.onclick=start;stopBtn.onclick=stop;controlBtn.onclick=()=>{control=!control;controlBtn.textContent=control?'◎ Desactivar control':'◎ Activar control';log(`Control virtual ${control?'activado':'desactivado'}`,'ok');speech.innerHTML=control?'☝️ Ahora tu índice mueve el cursor. Haz pinza para clicar.':'Control virtual desactivado.'};
$('trainingBtn').onclick=()=>{mission=0;missionProgress=0;updateMission();speech.innerHTML='🎮 Modo entrenamiento listo. Completa las 4 misiones.';log('Modo entrenamiento reiniciado')};
$('demoBtn').onclick=()=>{demo=!demo;control=demo||control;playground.classList.toggle('demo-on',demo);$('demoBtn').textContent=demo?'✨ Salir modo demo':'✨ Modo demo';labStatus.textContent=demo?'INTERACCIÓN ACTIVA':'Activa Modo demo';controlBtn.disabled=!running;controlBtn.textContent=control?'◎ Desactivar control':'◎ Activar control';speech.innerHTML=demo?'✨ Modo demo activo: pinza para agarrar, mano abierta para swipe y dos manos para zoom.':'Modo demo desactivado.';showToast(demo?'✨ Interacción activa':'Modo demo apagado');log(`Modo demo ${demo?'activado':'desactivado'}`,'ok')};
$('clearLog').onclick=()=>{$('log').innerHTML='<div>Registro limpiado.</div>'};$('soundBtn').onclick=()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'🔊':'🔇'};$('fullscreenBtn').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()};
updateXP();updateMission();